### PR TITLE
fix: correct useZohoAuth import extension in useContactPersons

### LINKED ISSUE #23: feat: view contact persons for a customer (read-only)
## User Value

Users can expand any customer row to see who the contact persons are.

## Background

The Lions Portal uses Zoho Invoice "contact persons" to link customers together — individual members are customers, and they are linked to club/organization customers as contact persons. This is the first increment of the Contact Person Management epic, delivering read-only visibility.

## Scope

- Add `fetchContactPersons` API helper to `src/lib/zohoApi.js`
  - `GET /contacts/{contactId}/contactpersons?organization_id={orgId}`
- Add `useContactPersons(contactId)` hook in new `src/hooks/useContactPersons.js`
  - Lazy: only fetches when a row is expanded (avoids N+1 on page load)
- Add `expandedRows` state to `CustomerTable.jsx` with a leading chevron toggle column (`▶`/`▼`)
- New `ContactPersonsPanel.jsx` — read-only Mantine `Table` of persons rendered inside an expansion row spanning all columns
  - Columns: First Name, Last Name, Email, Phone, Mobile, Primary, Notify
  - Empty state: "No contact persons" message + non-functional `+ Add` placeholder
- Collapse expanded rows on page navigation

## UI Sketch

```
▶ Acme Corp   acme@co.com   555-111   123 Main St
▼ Beta LLC    beta@co.com   555-222   456 Oak Ave
  └─ Contact Persons:
     ┌──────────────────────────────────────────────────────────────┐
     │  First Name  Last Name   Email        Phone   Primary  Notif │
     ├──────────────────────────────────────────────────────────────┤
     │  Jane        Doe         jane@co.com  555-11  ★        ✓    │
     │  John        Doe         john@co.com  555-22           ✓    │
     └──────────────────────────────────────────────────────────────┘
```

## Files Changed

| File | Change |
|------|--------|
| `src/lib/zohoApi.js` | Add `fetchContactPersons` |
| `src/hooks/useContactPersons.js` | New file — `useContactPersons` hook |
| `src/components/CustomerTable.jsx` | `expandedRows` state + expansion row render |
| `src/components/ContactPersonsPanel.jsx` | New file — read-only sub-table |

## Verification

- Expand a customer row → sub-table appears with correct contact persons
- Expand a customer with no persons → empty state with placeholder button shown
- Navigate to next page → previously expanded rows collapse

### PR DESCRIPTION
**Pull request by 4U6U57**
## Problem

The deploy after #28 failed with:

```
Could not resolve "./useZohoAuth.js" from "src/hooks/useContactPersons.js"
```

`useContactPersons.js` imported `./useZohoAuth.js` but the file is `useZohoAuth.jsx`. This resolves silently on macOS (case-insensitive filesystem) but breaks on Linux CI.

## Fix

Change the import extension from `.js` → `.jsx`, matching every other file in the hooks directory.

## Related

Fixes the broken deploy from #28. Closes #23 (the feature will now actually reach production).

### CODE REVIEW

File: src/hooks/useContactPersons.js [hunk 1]
```diff
@@ -1,5 +1,5 @@
 import { useQuery } from '@tanstack/react-query'
-import { useZohoAuth } from './useZohoAuth.js'
+import { useZohoAuth } from './useZohoAuth.jsx'
```
Comment (4U6U57) [inline src/hooks/useContactPersons.js]: Can we add a linter or test to avoid this issue in the future?
